# Generated by Django 4.1 on 2022-08-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('people', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=700)),
            ],
        ),
    ]
